name: Continuous Integration

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - "main"
  push:
    branches:
      - "release/*"

jobs:
  build:
    name: Build Artifact
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug
        run: |
          echo "GITHUB_REF  = $GITHUB_REF"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
      - name: Prepare artifact
        id: prep
        run: |
          mkdir -p dist
          touch dist/test.txt
          BUILD_NUM=$(echo $GITHUB_RUN_NUMBER)
          BUILD_ID=$(echo $GITHUB_SHA | head -c7)
          RELEASE=${GITHUB_REF#refs/heads/release/}
          VERSION=${RELEASE}+build.${BUILD_NUM}.${BUILD_ID}
          ARTIFACT_NAME=artifact_${VERSION}
          zip -r ${ARTIFACT_NAME}.zip dist/
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=artifact_name::${ARTIFACT_NAME}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.prep.outputs.artifact_name }}
          path: ${{ steps.prep.outputs.artifact_name }}.zip
          retention-days: 1
    outputs:
      version: ${{ steps.prep.outputs.version}}
      artifact_name: ${{ steps.prep.outputs.artifact_name }}
