# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   prep:
#     name: Prepare Build
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Prepare
#         id: prep
#         run: |
#           BUILD_ID=$(echo $GITHUB_SHA | head -c7)
#           echo ::set-output name=build_id::${BUILD_ID}
#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v1
#         with:
#           install: true
#       - name: Cache Docker Layers
#         uses: actions/cache@v2
#         with:
#           path: /tmp/.buildx-cache
#           key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-multi-buildx
#       - name: Build Workspace Image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           builder: ${{ steps.buildx.outputs.name }}
#           file: .devcontainer/Dockerfile
#           target: workspace
#           tags: alz-workspace:latest
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
#       - name: Move cache
#         run: |
#           rm -rf /tmp/.buildx-cache
#           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        
  lint:
    name: Lint
#     needs: prep
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Run lint stage
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .devcontainer/Dockerfile
          target: lint
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  securityScan:
    name: Security Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Run security scan stage
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .devcontainer/Dockerfile
          target: scan
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build:
    name: Build Artifact
    needs: [lint, securityScan]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Run build stage
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .devcontainer/Dockerfile
          target: builder
          tags: alz-builder
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
      - name: Build
        run: |
          docker run -v ${GITHUB_WORKSPACE}:/workspace alz-builder make build
#       - name: Prepare artifact
#         id: prep
#         run: |
#           BUILD_ID=$(echo $GITHUB_SHA | head -c7)
#           TEST_REFS=refs/heads/release/1.0.0
#           VERSION=${TEST_REFS#refs/heads/release/}
#           echo ::set-output name=version::${VERSION}-${BUILD_ID}
      - name: Prepare artifact
        id: prep
        run: |
          BUILD_NUM=$(echo $GITHUB_RUN_NUMBER)
          BUILD_ID=$(echo $GITHUB_SHA | head -c7)
          TEST_REFS=refs/heads/release/1.0.0
          RELEASE=${TEST_REFS#refs/heads/release/}
          VERSION=${RELEASE}+build.${BUILD_NUM}.${BUILD_ID}
          ARTIFACT_NAME=aws-landing-zone_${VERSION}.zip
          zip -r ${ARTIFACT_NAME}.zip dist/
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=artifact_name::${ARTIFACT_NAME}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.prep.outputs.artifact_name }}
          path: ${{ steps.prep.outputs.artifact_name }}.zip
          retention-days: 1
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.prep.outputs.artifact_name }}
      - name: Extract
        env: 
          ARTIFACT_NAME: ${{ steps.prep.outputs.artifact_name }}
        run: |
          ls -al
          unzip ${ARTIFACT_NAME}.zip
          mv dist/Makefile Makefile
          ls -al dist

#   publish:
#     name: Publish
#     needs: build
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Download build artifact
#         uses: actions/download-artifact@v2
#       - name: Move Makefile
#         run: |
#           mv dist/Makefile Makefile
#       - name: Set AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-region: us-east-1
#           aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
#           role-to-assume: CICDServiceRole
#       - name: Publish release artifact
#         run: |
#           BUILD_ID=$(echo $GITHUB_SHA | head -c7)
#           BRANCH_ARR=($(echo "$GITHUB_REF" | tr '/' '\n'))
#           VERSION=$(echo "$BRANCH_ARR[4]")
#           ls -al dist
#           zip -r snapshot.zip dist/
#           aws s3 cp snapshot.zip s3://com.laudio.releases/infrastructure/aws-landing-zone/$VERSION-$BUILD_ID.zip
          
